services:
  dns:
    image: "versioned-dns:1.0.0"
    build:
      context: ./
      target: production
    env_file: stack.env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    # volumes:
    #   - "./srv:/srv"
